export const ANALYTICS_REQUEST = "ANALYTICS_REQUEST";
export const ANALYTICS_SUCCESS = "ANALYTICS_SUCCESS";
export const ANALYTICS_FAIL = "ANALYTICS_FAIL";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const UPDATE_USER_ROLE_REQUEST = "UPDATE_USER_ROLE_REQUEST";
export const UPDATE_USER_ROLE_SUCCESS = "UPDATE_USER_ROLE_SUCCESS";
export const UPDATE_USER_ROLE_FAIL = "UPDATE_USER_ROLE_FAIL";

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_USER_ROLE_FAIL";

export const ADMIN_ALL_PRODUCT_REQUEST = "ADMIN_ALL_PRODUCT_REQUEST";
export const ADMIN_ALL_PRODUCT_SUCCESS = "ADMIN_ALL_PRODUCT_SUCCESS";
export const ADMIN_ALL_PRODUCT_FAIL = "ADMIN_ALL_PRODUCT_FAIL";

export const ADMIN_ALL_USER_REQUEST = "ADMIN_ALL_USER_REQUEST";
export const ADMIN_ALL_USER_SUCCESS = "ADMIN_ALL_USER_SUCCESS";
export const ADMIN_ALL_USER_FAIL = "ADMIN_ALL_USER_FAIL";

export const ADMIN_ALL_ORDER_REQUEST = "ADMIN_ALL_ORDER_REQUEST";
export const ADMIN_ALL_ORDER_SUCCESS = "ADMIN_ALL_ORDER_SUCCESS";
export const ADMIN_ALL_ORDER_FAIL = "ADMIN_ALL_ORDER_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MSG = "CLEAR_MSG";