export const ALL_CATEGORY_REQUEST = "ALL_CATEGORY_REQUEST";
export const ALL_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS";
export const ALL_CATEGORY_FAIL = "ALL_CATEGORY_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const FRONTPAGE_CATEGORY_REQUEST = "FRONTPAGE_CATEGORY_REQUEST";
export const FRONTPAGE_CATEGORY_SUCCESS = "FRONTPAGE_CATEGORY_SUCCESS";
export const FRONTPAGE_CATEGORY_FAIL = "FRONTPAGE_CATEGORY_FAIL";